export const ENV_VAR = {
  GRANT_TYPE: process.env.NEXT_PUBLIC_GRANT_TYPE,
  AUTH0_CLIENT_SECRET: process.env.NEXT_PUBLIC_AUTH0_CLIENT_SECRET,
  AUTH0_CLIENT_ID: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID,
  AUTH0_ISSUER: process.env.NEXT_PUBLIC_AUTH0_ISSUER
}
